require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native/scripts/react_native_codegen_pods'

platform :ios, '13.0'

# Production 모드
production = true

use_react_native!(
  :path => config[:reactNativePath],
  :app_path => "#{Pod::Config.instance.installation_root}/..",
  :fabric_enabled => false,        # Fabric OFF
  :hermes_enabled => true,         # Hermes ON
  :production => production,
  :codegen_path => "../build/generated/ios" # Codegen 출력 경로
)

# 모든 Pod 설치 후 RN Codegen 경로 symlink 처리
post_install do |installer|
  react_native_post_install(installer)
  
  # CI에서 Pod headers 문제 방지용 symlink
  generated_dir = File.join(installer.sandbox.root, 'Headers/Public/React-Codegen')
  build_dir = File.expand_path('../build/generated/ios', __dir__)
  FileUtils.mkdir_p(File.dirname(generated_dir))
  FileUtils.ln_sf(build_dir, generated_dir)
  puts "✅ React-Codegen symlink created: #{generated_dir} -> #{build_dir}"
end