source 'https://cdn.cocoapods.org/'


require_relative '../node_modules/react-native/scripts/react_native_pods'


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
'node',
['-p',
'require.resolve(
"react-native/scripts/react_native_pods.rb",
{paths: [process.argv[1]]},
)', __dir__]
).strip


platform :ios, min_ios_version_supported
prepare_react_native_project!


linkage = ENV['USE_FRAMEWORKS']
if linkage
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
end


target 'humake_app' do
config = use_native_modules!


use_react_native!(
:path => config[:reactNativePath],
:app_path => "#{Pod::Config.instance.installation_root}/.."
)


pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'


post_install do |installer|
react_native_post_install(
installer,
config[:reactNativePath],
:mac_catalyst_enabled => false
)
end
end

post_install do |installer|
react_native_post_install(installer)


# 시뮬레이터 arm64 제외 (Intel Mac CI용)
installer.pods_project.build_configurations.each do |config|
config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
end